### ISSUE TITLE
meshconfig-agent throws error trying to connect to IPv6 address

### ISSUE THREAD

**Issue by arlake228** [perfsonar/mesh-config#95]
@owens-bill reported the following in perfsonar/pscheduler#233. Looks like maybe the meshconfig-agent is having a problem when you give it a raw IPv6 address: 

2017/04/27 10:29:50 (3145) WARN> perfsonar_meshconfig_agent:430 main:: - Problem adding test, continuing with rest of config: 500 Can't connect to 2620:f:0:915::3: Can't connect to 2620:f:0:915::3

Name or service not known at /usr/share/perl5/LWP/Protocol/http.pm line 51.

**Comment by akurov** [comment]
Hi all,

This bug should be fixed in 4.0.1? 

$ rpm -q perfsonar-meshconfig-agent
perfsonar-meshconfig-agent-4.0.1-1.el7.centos.noarch

I still see such errors in /var/log/perfsonar/meshconfig-agent.log

2017/11/10 17:54:32 (1392) WARN> perfsonar_meshconfig_agent:430 main:: - Problem adding test throughput(2001:db8::1->psmp-gn-bw-01-fra-de.geant.net), continuing with rest of config: 500 Can't connect to 2001:db8::1:443: Can't connect to 2001:db8::1:443

Connection refused at /usr/share/perl5/LWP/Protocol/http.pm line 51.
